server {
    listen 80;
    server_name _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Necessary for Single Page Applications (like React Router)
        try_files $uri $uri/ /index.html;
    }

    # Optional: proxy api requests to backend
    # location /api/ {
    #     proxy_pass http://backend:3000/;
    # }
}
